# Etapa 1: Build
FROM node:18 AS build

WORKDIR /app

# PASO CLAVE: define y usa la variable de entorno
ARG VITE_BACKEND_URL
ARG VITE_INTERNAL_API_KEY
ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}
ENV VITE_INTERNAL_API_KEY=${VITE_INTERNAL_API_KEY}

COPY . .
RUN npm install
RUN npm run build

# Etapa 2: Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
