version: '3.8'

services:
  mysql:
    image: mysql:8  # Usa la versión más reciente
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Cambia por una contraseña segura
      MYSQL_DATABASE: store
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      PORT: "3001"
      FRONTEND_URL: http://localhost:3000
      SECRET_KEY: secret
      INTERNAL_API_KEY: SG9sYU11bmRv*
      EMAIL_USER: vinotecavinoteca123@gmail.com
      EMAIL_PASS: 'wsqo bjmx pxax fgis'
      EMAIL_ADMIN: admin@admin.com
      PASSWORD_ADMIN: SG9sYU11bmRv*
      DATABASE_URL: "mysql://root:rootpassword@mysql:3306/store?schema=public"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment: 
      VITE_BACKEND_URL: http://localhost:3001
      VITE_INTERNAL_API_KEY: SG9sYU11bmRv*
      VITE_PORT: 80
    restart: always

volumes:
   mysql_data: